DROP VIEW IF EXISTS technicals_daily;

CREATE TABLE IF NOT EXISTS technicals_daily (
    ticker              VARCHAR NOT NULL,
    date                DATE    NOT NULL,
    adjusted_close      DOUBLE,
    sma_20              DOUBLE,
    sma_50              DOUBLE,
    sma_200             DOUBLE,
    high_52w            DOUBLE,
    low_52w             DOUBLE,
    realized_vol_60d    DOUBLE,
    beta_252d           DOUBLE,
    ema_12              DOUBLE,
    ema_26              DOUBLE,
    ema_50              DOUBLE,
    pct_from_sma_50     DOUBLE,
    pct_from_sma_200    DOUBLE,
    rsi_14              DOUBLE,
    macd                DOUBLE,
    macd_signal         DOUBLE,
    macd_histogram      DOUBLE,
    bb_middle           DOUBLE,
    bb_upper            DOUBLE,
    bb_lower            DOUBLE,
    bb_width            DOUBLE,
    atr_14              DOUBLE,
    volume_sma_50       DOUBLE,
    volume_ratio        DOUBLE,
    pct_from_52w_high   DOUBLE,
    pct_from_52w_low    DOUBLE,
    loaded_at           TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (ticker, date)
);
