import { useEffect, useMemo, useState } from "react";

import { runFundamentalScreen, type TableResponse } from "../../api/client";
import { DataGrid } from "../../components/DataGrid";
import { useActiveWatchlist } from "../watchlists/ActiveWatchlist";
import { SaveScreenResults, ScreenerFilterForm, type FilterField } from "./ScreenerControls";

type ScreenDefinition = { key: string; label: string; description: string; fields: FilterField[] };
const sizeFields: FilterField[] = [
  { key: "min_mktcap_b", label: "Min market cap ($B)", type: "number", min: 0.1, max: 5000, step: 1, optional: true },
  { key: "min_adtv_m", label: "Min avg daily volume ($M)", type: "number", min: 0.1, max: 500, step: 1, optional: true },
];
const screens: ScreenDefinition[] = [
  { key: "absolute_valuation", label: "Absolute valuation", description: "Filter by absolute multiple ceilings and an FCF-yield floor.", fields: [{ key: "max_pe", label: "Max P/E", type: "number", min: 1, max: 200, optional: true }, { key: "max_ps", label: "Max P/S", type: "number", min: 0.1, max: 50, step: 0.5, optional: true }, { key: "max_pb", label: "Max P/B", type: "number", min: 0.1, max: 50, step: 0.5, optional: true }, { key: "max_ev_ebitda", label: "Max EV / EBITDA", type: "number", min: 1, max: 100, optional: true }, { key: "min_fcf_yield", label: "Min FCF yield (%)", type: "number", min: 0.1, max: 20, step: 0.5, optional: true }] },
  { key: "relative_history", label: "Relative to own history", description: "Find multiples that are low relative to each ticker’s own valuation history.", fields: [{ key: "years", label: "History window (years)", type: "number", min: 1, max: 10, defaultValue: 5 }, { key: "max_pe_rank", label: "Max P/E rank (%)", type: "number", min: 1, max: 99, step: 5, optional: true }, { key: "max_ev_rank", label: "Max EV / EBITDA rank (%)", type: "number", min: 1, max: 99, step: 5, optional: true }, { key: "max_ps_rank", label: "Max P/S rank (%)", type: "number", min: 1, max: 99, step: 5, optional: true }, { key: "min_history_days", label: "Min history days", type: "number", min: 0, max: 2000, step: 63, defaultValue: 252 }] },
  { key: "growth", label: "Growth", description: "Filter revenue and earnings growth, with an optional four-quarter acceleration check.", fields: [{ key: "min_rev_yoy", label: "Min revenue YoY (%)", type: "number", min: -50, max: 200, step: 5, optional: true }, { key: "min_eps_yoy", label: "Min EPS YoY (%)", type: "number", min: -50, max: 200, step: 5, optional: true }, { key: "require_acceleration", label: "Require revenue acceleration (4 quarters)", type: "boolean" }] },
  { key: "quality", label: "Quality", description: "Filter returns, margin quality, and free-cash-flow conversion.", fields: [{ key: "min_roe", label: "Min ROE (%)", type: "number", min: 0, max: 200, step: 5, optional: true }, { key: "min_roic", label: "Min ROIC (%)", type: "number", min: 0, max: 100, step: 5, optional: true }, { key: "min_gross_margin", label: "Min gross margin (%)", type: "number", min: 0, max: 100, step: 5, optional: true }, { key: "min_fcf_conversion", label: "Min FCF conversion (%)", type: "number", min: 0, max: 300, step: 10, optional: true }, { key: "require_margin_expansion", label: "Require gross-margin expansion", type: "boolean" }] },
  { key: "balance_sheet", label: "Balance-sheet strength", description: "Filter leverage, interest coverage, and liquidity.", fields: [{ key: "max_net_debt_ebitda", label: "Max net debt / EBITDA", type: "number", min: -10, max: 20, step: 0.5, optional: true }, { key: "min_interest_coverage", label: "Min interest coverage", type: "number", min: 0, max: 100, optional: true }, { key: "min_current_ratio", label: "Min current ratio", type: "number", min: 0, max: 10, step: 0.25, optional: true }] },
  { key: "income", label: "Income", description: "Filter dividend yield, payout ratio, and dividend-history depth.", fields: [{ key: "min_yield", label: "Min dividend yield (%)", type: "number", min: 0.1, max: 20, step: 0.5, optional: true }, { key: "max_payout", label: "Max payout ratio (%)", type: "number", min: 1, max: 200, step: 5, optional: true }, { key: "min_div_years", label: "Min dividend-history years", type: "number", min: 1, max: 50, defaultValue: 5, optional: true }] },
];

export function FundamentalScreenerPage() {
  const { id } = useActiveWatchlist(); const [screenKey, setScreenKey] = useState(screens[0].key); const [filters, setFilters] = useState<Record<string, unknown>>({}); const [data, setData] = useState<TableResponse | null>(null); const [loading, setLoading] = useState(true); const [error, setError] = useState<string | null>(null);
  const screen = useMemo(() => screens.find((item) => item.key === screenKey) ?? screens[0], [screenKey]);
  async function run(nextFilters = filters) { setLoading(true); setError(null); try { setData(await runFundamentalScreen(screen.key, nextFilters, id)); } catch (reason) { setError(reason instanceof Error ? reason.message : "Unable to run screen."); } finally { setLoading(false); } }
  useEffect(() => { void run({}); }, [screen.key, id]);
  return <main className="shell screener-shell"><header><p className="eyebrow">Fundamentals dashboard</p><h1>Fundamental screens</h1><p className="lede">Find companies on trailing valuation, quality, growth, balance-sheet, and income signals.</p></header><section className="workbench"><aside aria-label="Fundamental screen filters"><label>Screen<select value={screen.key} onChange={(event) => { setScreenKey(event.target.value); setFilters({}); }}>{screens.map((item) => <option value={item.key} key={item.key}>{item.label}</option>)}</select></label><p className="filter-description">{screen.description}</p><ScreenerFilterForm formKey={screen.key} fields={[...sizeFields, ...screen.fields]} onSubmit={(next) => { setFilters(next); void run(next); }} /></aside><ScreenContent data={data} error={error} loading={loading} onError={setError} /></section></main>;
}

function ScreenContent({ data, error, loading, onError }: { data: TableResponse | null; error: string | null; loading: boolean; onError: (message: string) => void }) { return <section className="results" aria-busy={loading}><div className="results-head"><h2>Matches</h2>{data && <span>{data.total ?? data.rows.length} companies</span>}</div>{error ? <p className="notice error" role="alert">{error}</p> : loading ? <div className="skeleton" aria-label="Loading results" /> : data?.rows.length ? <><DataGrid data={data} onTickerSelect={(ticker) => { window.location.href = `/company?ticker=${encodeURIComponent(ticker)}`; }} /><SaveScreenResults data={data} onError={onError} /></> : <div className="notice" role="status">No companies match the current filters.</div>}</section>; }
