import { useEffect, useMemo, useState } from "react";
import { DataGrid } from "../../components/DataGrid";
import { requestJson, runScreen, type TableResponse } from "../../api/client";
import { useActiveWatchlist } from "../watchlists/ActiveWatchlist";
import { SaveScreenResults, ScreenerFilterForm, type FilterField } from "./ScreenerControls";

type Definition = { key: string; label: string; description: string; group?: string; fields: FilterField[] };
const period: FilterField = { key: "period_filter", label: "Period", type: "select", defaultValue: "__all__", options: [{ label: "All", value: null }, { label: "Current Q (0q)", value: "0q" }, { label: "Next Q (+1q)", value: "+1q" }, { label: "Current Y (0y)", value: "0y" }, { label: "Next Y (+1y)", value: "+1y" }] };
const technicalSize: FilterField[] = [{ key: "min_mktcap_b", label: "Min market cap ($B)", type: "number", min: 0.1, max: 5000, optional: true }, { key: "min_adtv_m", label: "Min avg daily volume ($M)", type: "number", min: 0.1, max: 500, optional: true }];
const forward: Definition[] = [
  { key: "eps_revised_up", label: "EPS estimate revised up", group: "Vendor-provided trends", description: "Uses EODHD’s current 7- or 30-day estimate deltas; it works without accumulated snapshots.", fields: [{ key: "lookback_days", label: "Lookback", type: "select", defaultValue: "30", options: [{ label: "7 days", value: 7 }, { label: "30 days", value: 30 }] }, { key: "min_delta_pct", label: "Min EPS delta (%)", type: "number", min: 0, max: 50, step: 0.5, defaultValue: 0 }, period] },
  { key: "net_upward_eps_revisions", label: "Net upward EPS revisions", group: "Vendor-provided trends", description: "Identifies estimate periods where upgrades exceed downgrades.", fields: [{ key: "lookback_days", label: "Lookback", type: "select", defaultValue: "30", options: [{ label: "7 days", value: 7 }, { label: "30 days", value: 30 }] }, { key: "min_net", label: "Min net upward revisions", type: "number", min: 1, max: 100, defaultValue: 3 }, period] },
  { key: "beat_and_revise", label: "Beat and raise", group: "Vendor-provided trends", description: "Requires a positive EPS surprise and an upward forward revision.", fields: [{ key: "min_surprise_pct", label: "Min EPS surprise (%)", type: "number", min: 0, max: 50, step: 0.5, defaultValue: 2 }, { key: "min_eps_delta_pct", label: "Min forward EPS delta (%)", type: "number", min: 0, max: 20, step: 0.5, defaultValue: 0 }] },
  { key: "consensus_rating_shift", label: "Consensus rating shift", group: "Snapshot history", description: "Compares latest consensus ratings with a snapshot from N days ago. 1 is Strong Buy; a negative shift is an upgrade.", fields: [{ key: "lookback_days", label: "Lookback days", type: "number", min: 7, max: 365, step: 7, defaultValue: 30 }, { key: "min_shift", label: "Min rating shift", type: "number", min: 0.1, max: 4, step: 0.1, defaultValue: 0.5 }, { key: "min_history_days", label: "Min snapshot-history days", type: "number", min: 30, max: 365, defaultValue: 30 }] },
  { key: "target_price_raised", label: "Target price raised", group: "Snapshot history", description: "Compares current target prices with snapshots from N days ago.", fields: [{ key: "lookback_days", label: "Lookback days", type: "number", min: 7, max: 365, step: 7, defaultValue: 30 }, { key: "min_change_pct", label: "Min target-price change (%)", type: "number", min: 0.1, max: 50, step: 0.5, defaultValue: 5 }, { key: "min_history_days", label: "Min snapshot-history days", type: "number", min: 30, max: 365, defaultValue: 30 }] },
];
const technical: Definition[] = [
  { key: "confirmed_uptrend", label: "Confirmed uptrend", description: "Price above SMA200 and SMA50 above SMA200.", fields: [] }, { key: "confirmed_downtrend", label: "Confirmed downtrend", description: "Price below SMA200 and SMA50 below SMA200.", fields: [] }, { key: "golden_cross_recent", label: "Golden cross (recent)", description: "SMA50 crossed above SMA200 within the selected window.", fields: [{ key: "lookback_days", label: "Lookback days", type: "number", min: 5, max: 90, defaultValue: 30 }] }, { key: "death_cross_recent", label: "Death cross (recent)", description: "SMA50 crossed below SMA200 within the selected window.", fields: [{ key: "lookback_days", label: "Lookback days", type: "number", min: 5, max: 90, defaultValue: 30 }] }, { key: "rsi_oversold", label: "RSI oversold", description: "RSI(14) below the selected threshold.", fields: [{ key: "threshold", label: "RSI threshold", type: "number", min: 10, max: 50, defaultValue: 30 }] }, { key: "rsi_overbought", label: "RSI overbought", description: "RSI(14) above the selected threshold.", fields: [{ key: "threshold", label: "RSI threshold", type: "number", min: 50, max: 90, defaultValue: 70 }] }, { key: "macd_bullish_crossover", label: "MACD bullish crossover", description: "MACD crossed above its signal line recently.", fields: [{ key: "lookback_days", label: "Lookback days", type: "number", min: 1, max: 20, defaultValue: 5 }] }, { key: "macd_bearish_crossover", label: "MACD bearish crossover", description: "MACD crossed below its signal line recently.", fields: [{ key: "lookback_days", label: "Lookback days", type: "number", min: 1, max: 20, defaultValue: 5 }] }, { key: "near_52w_high", label: "Near 52-week high", description: "Price is within N% of its 52-week high.", fields: [{ key: "pct_threshold", label: "Within % of 52-week high", type: "number", min: 1, max: 20, defaultValue: 5 }] }, { key: "near_52w_low", label: "Near 52-week low", description: "Price is within N% of its 52-week low.", fields: [{ key: "pct_threshold", label: "Within % of 52-week low", type: "number", min: 1, max: 20, defaultValue: 5 }] }, { key: "bb_squeeze", label: "Bollinger Band squeeze", description: "Band width below its own 252-day percentile threshold.", fields: [{ key: "percentile", label: "BB-width percentile", type: "number", min: 5, max: 50, defaultValue: 20 }] }, { key: "volume_spike", label: "Volume spike", description: "Volume is N× the 50-day average.", fields: [{ key: "threshold", label: "Volume ratio threshold", type: "number", min: 1.5, max: 10, step: 0.5, defaultValue: 2 }] },
];

export function GenericScreenerPage({ family }: { family: "forward" | "technical" }) {
  const { id } = useActiveWatchlist(); const definitions = family === "forward" ? forward : technical; const [screenKey, setScreenKey] = useState(definitions[0].key); const [filters, setFilters] = useState<Record<string, unknown>>({}); const [data, setData] = useState<TableResponse | null>(null); const [error, setError] = useState<string | null>(null); const [notice, setNotice] = useState<string | null>(null); const [loading, setLoading] = useState(true); const [recomputing, setRecomputing] = useState(false); const screen = useMemo(() => definitions.find((item) => item.key === screenKey) ?? definitions[0], [definitions, screenKey]);
  async function load(next = filters) { setLoading(true); setError(null); try { setData(await runScreen(family, screen.key, next, id)); } catch (reason) { setError(reason instanceof Error ? reason.message : "Unable to run screen."); } finally { setLoading(false); } }
  useEffect(() => { void load({}); }, [family, id, screen.key]);
  async function recompute() { setRecomputing(true); setError(null); setNotice(null); try { await requestJson<void>("technicals/recompute", "POST"); await load(); setNotice("Technicals updated from current price history."); } catch (reason) { setError(reason instanceof Error ? reason.message : "Unable to recompute technicals."); } finally { setRecomputing(false); } }
  return <main className="shell screener-shell"><header><p className="eyebrow">Fundamentals dashboard</p><h1>{family === "forward" ? "Forward screens" : "Technical screens"}</h1><p className="lede">{family === "forward" ? "Surface analyst-estimate revisions and snapshot-history signals." : "Surface price and indicator signals from the stored market history."}</p>{family === "technical" && <button disabled={recomputing} onClick={() => void recompute()}>{recomputing ? "Recomputing technicals…" : "Recompute technicals"}</button>}</header>{notice && <p className="notice success" role="status">{notice}</p>}<section className="workbench"><aside aria-label={`${family} screen filters`}>{family === "forward" && <p className="filter-description">Vendor trends work immediately. Snapshot-history screens require at least 30 daily observations.</p>}<label>Screen<select value={screen.key} onChange={(event) => { setScreenKey(event.target.value); setFilters({}); }}>{definitions.map((item) => <option key={item.key} value={item.key}>{item.group ? `${item.group}: ${item.label}` : item.label}</option>)}</select></label><p className="filter-description">{screen.description}</p><ScreenerFilterForm formKey={`${family}-${screen.key}`} fields={family === "technical" ? [...technicalSize, ...screen.fields] : screen.fields} onSubmit={(next) => { setFilters(next); void load(next); }} /></aside><section className="results" aria-busy={loading}><div className="results-head"><h2>Matches</h2>{data && <span>{data.total ?? data.rows.length} companies</span>}</div>{data && data.excluded_count > 0 && <p className="excluded-note" role="status">{data.excluded_count} tickers excluded for insufficient snapshot history.</p>}{error ? <p className="notice error" role="alert">{error}</p> : loading ? <div className="skeleton" aria-label="Loading results" /> : data?.rows.length ? <><DataGrid data={data} onTickerSelect={(ticker) => { window.location.href = `/company?ticker=${encodeURIComponent(ticker)}`; }} /><SaveScreenResults data={data} onError={setError} /></> : <div className="notice" role="status">No companies match the current filters.</div>}</section></section></main>;
}
